//
// BluamekBoard config
//
//
// (Key to detect), (X position), (Y position), (Width), (Height), (Color when key is NOT pressed), (Color when key is pressed) (Label inside of double quotes)
//
// Example:
// KEY_W, 110.0, 10.0, 60.0, 60.0, DARKGRAY, LIGHTGRAY, "W"
//
// Refer to https://docs.rs/keycodes/latest/keycodes/#constants for keycodes and docs.rs/macroquad/latest/macroquad/color/colors/index.html#constants for colors.

KEY_W, 110.0, 10.0, 60.0, 60.0, DARKGRAY, LIGHTGRAY, "W"
